# Generated by Django 5.0.6 on 2024-07-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyagevista', '0004_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_rating',
        ),
    ]
