# Generated by Django 5.0.6 on 2024-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyagevista', '0010_remove_rating_average_rating_alter_rating_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
