# Generated by Django 5.1 on 2024-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyagevista', '0016_alter_comment_options_remove_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Default content'),
        ),
    ]
