# Generated by Django 5.0.6 on 2024-07-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyagevista', '0002_remove_post_average_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
