# Generated by Django 5.0.6 on 2024-07-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyagevista', '0010_update_status_to_integers'),
        ('voyagevista', '0011_update_status_to_integers'),
    ]

    operations = [
    ]
