# Generated by Django 5.0.6 on 2024-07-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyagevista', '0009_alter_post_status'),
        ('voyagevista', '0012_merge_20240722_2051'),
    ]

    operations = [
    ]
